[package]
name = "fetch-all"
version = "1.0.0"
edition = "2021"
description = "Simple example that fetches all data from a UniFi controller"

[dependencies]
rustifi = { path = "../.." }
tokio = { version = "1", features = ["full"] }
